### ISSUE TITLE
Taller Flutter

### ISSUE THREAD

**Issue by JuanRamos26** [ISCOUTB/DG-UTB-Tools#1]
Vamos aprender flutter y que aprendimos
Escoger entre visual code, intellij IDEA

Tutorial Intellij IDEA
https://www.youtube.com/watch?v=rNgGMha2Uss

tutorial visual code
https://www.youtube.com/watch?v=Qkr3sRJXbls

Una vez definamos cual usaremos, les mandare unos videos, para aprender lo basico sobre el entorno de desarrollo que escojamos:

**Comment by JuanRamos26** [comment]
Compañeros...  he escogido Intellij Idea, como nuestro entorno de desarrollo, Ya que se me hace mas completo para lo que vamos a utilizar, ademas de una instalacion de flutter mas sencillla y completa.

![Image](https://github.com/user-attachments/assets/6e51abb8-920a-45de-9cb8-3bd21ebc519b)



![Image](https://github.com/user-attachments/assets/01ea4320-fb38-433f-a5a9-9451c1a612e2)



![Image](https://github.com/user-attachments/assets/9834b230-b491-4ed5-861b-b5dd0f61354f)

**Comment by Manuuell** [comment]
Tambien escogí Intellij Idea, como nuestro entorno de desarrollo
![Image](https://github.com/user-attachments/assets/13c9d18e-3c42-420f-8144-3b2eaa6d3c33)



![Image](https://github.com/user-attachments/assets/18dd9621-b3fe-43bb-8a53-d0868ad91bcf)



![Image](https://github.com/user-attachments/assets/b5de17e0-e63d-4f06-af70-d7489477560a)

**Comment by JuanRamos26** [comment]
![Image](https://github.com/user-attachments/assets/2d734981-8ee1-47a6-8462-d6b48ef2d1cd)
Escogí Intellij Idea como entorno de desarrollo

**Comment by jerdiaz** [comment]
![Image](https://github.com/user-attachments/assets/7953bf20-bc93-4176-8f08-3f0d04e269bd)
Escogí Intellij idea como entorno de desarrollo

**Comment by JuanRamos26** [comment]
Perfecto, Entonces ya esta creado el proyecto
![Image](https://github.com/user-attachments/assets/145f0cc7-9c78-4b57-9a88-df66a47ca403)

**Comment by jairoserrano** [comment]
Ok adelante con el desarrollo.
