### ISSUE TITLE
convertidor

### ISSUE THREAD

**Issue by JuanRamos26** [ISCOUTB/DG-UTB-Tools#11]
- [x] Diseño de la interfaz de usuario
- [x] Subir archivo en cualquier formato
- [x] Convertirlo a otro formato
- [x] Permitir descargar el archivo en el nuevo formato

**Comment by JuanRamos26** [comment]
Adjunto código del convertidor de archivos
![Image](https://github.com/user-attachments/assets/6344e77c-5162-43c7-bb61-9a7a2f0c2044)

**Comment by Manuuell** [comment]
vistazo de como se ve el convertidor funcionando 
![Image](https://github.com/user-attachments/assets/1af904ac-fef0-4527-b47d-ba096318dc14)
![Image](https://github.com/user-attachments/assets/dfb9b242-7238-46a6-85ab-22a6408b8fd2)
nos permite convertir a esos formatos

**Comment by JuanRamos26** [comment]
video de como funciona
https://github.com/user-attachments/assets/7108c47e-a7fd-4c78-97cd-41ff9f1267a6
