### ISSUE TITLE
HorarioClases

### ISSUE THREAD

**Issue by JuanRamos26** [ISCOUTB/DG-UTB-Tools#12]
- [x] Permitir ingresar las materias
- [x] crear el horario

**Comment by Manuuell** [comment]
![Image](https://github.com/user-attachments/assets/78179ef4-723f-4e14-9cd6-a23e3b283cc2)

**Comment by Manuuell** [comment]
Asi se veria implementado en la web
![Image](https://github.com/user-attachments/assets/a837feb6-8a86-4f66-8b82-4452445fdceb)

**Comment by JuanRamos26** [comment]
Adjunto una parte del codigo del horario


![Image](https://github.com/user-attachments/assets/f3d9f917-a0da-452c-ad73-a06aad5ca415)
![Image](https://github.com/user-attachments/assets/b5d168b8-3d62-4d16-85ad-ef5dc25854ec)
![Image](https://github.com/user-attachments/assets/63c02cfc-cccd-4e48-a4ca-44f465824e35)

**Comment by JuanRamos26** [comment]
Video de como funciona el horario
https://github.com/user-attachments/assets/50e5cc45-1259-4b1f-a4ff-4a0fb120fd8d
