### ISSUE TITLE
mejorar diseño calcular nota

### ISSUE THREAD

**Issue by jerdiaz** [ISCOUTB/DG-UTB-Tools#14]
Mejorar diseño de wireframe de nota

**Comment by jerdiaz** [comment]
![IMG-20241002-WA0028.jpg](https://github.com/user-attachments/assets/47da0f87-f4c2-49be-9fde-c7e9127b0785)

**Comment by JuanRamos26** [comment]
Listo, el diseño se ha mejorado, y se actualizo en github, con un commit
 ![Image](https://github.com/user-attachments/assets/87530dc2-25c3-4e31-b78f-8c7c0bc299db)

![Image](https://github.com/user-attachments/assets/15333494-e98e-4bf7-8fbf-1ab7c6d662d7)
