### ISSUE TITLE
Agregar validaciones de entrada en "Calcular Nota"

### ISSUE THREAD

**Issue by Manuuell** [ISCOUTB/DG-UTB-Tools#15]
Agregar validaciones

- [x] No permitir ingresar letras.
- [x] No permitir coma (,) ni símbolos diferentes al punto.

**Comment by JuanRamos26** [comment]
Listo, codigo actualizado en github
![Image](https://github.com/user-attachments/assets/1c05b502-d416-4780-bcc4-01c9bb2be3b4)

**Comment by jerdiaz** [comment]
Validaciones agregadas.
![IMG-20241002-WA0027.jpg](https://github.com/user-attachments/assets/8a394ca0-0c3e-403f-8b68-e2f98e46c88f)
