### ISSUE TITLE
Desarrollo del Backend o Api

### ISSUE THREAD

**Issue by JuanRamos26** [ISCOUTB/DG-UTB-Tools#2]
Definir si se va a utilizar
- FastApi
- Flask

Depues de buscar en internet encontre esto:

Flask
Flask es el segundo framework más popular de Python, el foco principal de éste es ser más liviano y flexible, basándose en la simplicidad. Flask deja todas las decisiones en manos del desarrollador, con las ventajas y/o desventajas que eso implica.

Ventajas
- Fácil para comenzar en un principio.

- Bastante flexibilidad en cuanto a cómo estructurar el código.

- Es fácil agregar, modificar o sacar código.

Desventajas
- Pocos features soportados por defecto por lo que requiere instalación de varios paquetes externos y el posterior mantenimiento de los mismos, por ende, el desarrollador tiene que encargarse de mantenerlos actualizados y compatibles con el código propio.

- Al ser tan liviano y simple, no es la mejor opción para hacer proyectos grandes. 

FastAPI
FastAPI es un framework moderno, rápido y robusto creado con la idea de aprovechar de forma nativa los type-hints de Python, enfocándose en la performance y en las necesidades de las aplicaciones de la actualidad. Esta construido sobre Starlette y Pydantic, lo que le permite soportar de forma nativa numerosos features y que la developer-experience sea la mejor posible.

Ventajas
- Fácil para comenzar en un principio.

- Bastante flexibilidad en cuanto a cómo estructurar el código.

- Es fácil agregar, modificar o eliminar código.

- ASGI soportado de forma nativa.

- Documentación autogenerada a partir de anotaciones.

- Validación de tipos, incluso en JSON anidados.

- Inyección de dependencias para validaciones automáticas.

- Excelente performance.

- Posibilidad de ser utilizado en proyectos de cualquier tamaño.

Desventajas
- Es un framework bastante nuevo, por lo tanto la comunidad no es tan grande y el material educativo (libros, cursos, ejemplos) no es tan extenso como en otros casos.

- El código no es estandarizado entre las diferentes empresas.

- La documentación oficial no es tan profunda, por lo que hacer implementaciones no tan triviales requiere un esfuerzo extra a la hora de resolver problemas o desafíos de implementación.

**Comment by JuanRamos26** [comment]
Cualquiera de las dos me parece una buena api, pero por el tipo de proyecto diría que fastApi es la mejor opcion

**Comment by Manuuell** [comment]
concuerdo con el compañero, me parece buena opción fastApi

**Comment by jairoserrano** [comment]
Ok adelante con el desarrollo.
