### ISSUE TITLE
Definir wireframes de toda la aplicacion

### ISSUE THREAD

**Issue by JuanRamos26** [ISCOUTB/DG-UTB-Tools#3]
Aprender a usar figma, hacer el diseño

Curso corto de figma: https://www.youtube.com/playlist?list=PLvq-jIkSeTUbpfewvbKLhHctdkgadAy-K
Pueden buscar en otras fuentes, o otros cursos, Pero igualmente... Lo importante es aprender lo basico de figma para hacer el wireframe, o el boceto de la aplicacion

**Comment by JuanRamos26** [comment]
usaremos figma para hacer el wireframes de lo que queremos llegar:

![Image](https://github.com/user-attachments/assets/52886f23-5ac7-469a-b249-a8b4b5dca85f)

**Comment by Manuuell** [comment]
Revisé el curso y esta completo. esta semana tendremos avances del modelado

**Comment by jerdiaz** [comment]
Después de revisar el curso de figma, puedo concluir que el curso está bastante completo

**Comment by JuanRamos26** [comment]
Usaremos figma entonces para hacer el wireframes

**Comment by jairoserrano** [comment]
Esperaré al wireframe entonces. por ahora esta tarea regresa a en progreso.

**Comment by JuanRamos26** [comment]
wireframe del menu principal

![Image](https://github.com/user-attachments/assets/b386af2b-2ca5-492f-8105-8a9db4c35070)

**Comment by Manuuell** [comment]
avances de la pagina de inicio 
![Image](https://github.com/user-attachments/assets/da2c350e-f0dd-4369-a33d-e5a08af520a1)

**Comment by JuanRamos26** [comment]
Wireframes listos, y adjutando en otras tareas, utilizamos figma para hacerlos

**Comment by jairoserrano** [comment]
ok, revisamos las demas.
