### ISSUE TITLE
Wireframes #1 (menu principal)

### ISSUE THREAD

**Issue by JuanRamos26** [ISCOUTB/DG-UTB-Tools#4]
Hacer el wireframe del proyecto, en figma, para eso luego de haber visto el curso, en nuestro equipo de figma van a empezar a diseñar:
 ![Image](https://github.com/user-attachments/assets/ff9ab736-f954-415a-ade0-6aa219e2f2c3)

**Comment by Manuuell** [comment]
![Image](https://github.com/user-attachments/assets/62d8786b-eafa-4f02-844e-f6a0f1265025)

**Comment by jerdiaz** [comment]
![Image](https://github.com/user-attachments/assets/21b2594f-6e2d-4363-bea0-dd7d5b4434ac)
menú de UTB Tools en móvil.

**Comment by Manuuell** [comment]
![Image](https://github.com/user-attachments/assets/8dbecfa5-ac5b-4205-ac11-ddb5a1d9a2f9)

**Comment by jairoserrano** [comment]
adelante
