### ISSUE TITLE
Menu principal

### ISSUE THREAD

**Issue by JuanRamos26** [ISCOUTB/DG-UTB-Tools#5]
Luego de hacer el diseño, van a expotarlo a flutter, para eso les he dejado estos videos: 

1.  https://www.youtube.com/watch?v=J8UoUWmVWbw
2.  https://www.youtube.com/watch?v=ookWwtF7GX8

este es nuestro proyecto en IntelliJ Idea:
![Image](https://github.com/user-attachments/assets/14f76dae-6365-458f-98a2-a40fa3c1024d)

**Comment by JuanRamos26** [comment]
Adjunto wireframe en un entorno web, funcional ya en Flutter: 

![Image](https://github.com/user-attachments/assets/6c4e5747-db7c-4945-8b3b-861c38876508)

**Comment by JuanRamos26** [comment]
menu principal acorde al WireFrame

![Image](https://github.com/user-attachments/assets/f89f6445-125f-4256-80c9-06cd0502a032)

**Comment by jairoserrano** [comment]
adelante.
