### ISSUE TITLE
NotaFinal

### ISSUE THREAD

**Issue by JuanRamos26** [ISCOUTB/DG-UTB-Tools#6]
- [x] Pedir nota corte 1 y corte 2
- [x] Calcular la nota minima para ganar

**Comment by Manuuell** [comment]
Se esta implementando la funcion CALCULA TU NOTA, este codigo puede tener cambios en proximas actualizaciones.
![Image](https://github.com/user-attachments/assets/53713c9b-b559-4901-918e-38391f7fc052)
![Image](https://github.com/user-attachments/assets/97f5c51d-115d-4733-987d-9fe0e9cc2f19)

**Comment by JuanRamos26** [comment]
Perfecto, un poco de como se calcula la nota

![Image](https://github.com/user-attachments/assets/923cfed6-4760-4106-8ac6-8573ef805b11)

**Comment by JuanRamos26** [comment]
https://github.com/user-attachments/assets/769a068a-519b-4079-98ac-5b7d1844017c

**Comment by jairoserrano** [comment]
adelante
