### ISSUE TITLE
Subir codigo en github

### ISSUE THREAD

**Issue by JuanRamos26** [ISCOUTB/DG-UTB-Tools#7]
Subir los archivos del código en GitHub para ir trabajando en conjunto, creando el repositorio, y se actualicen los cambios y versiones

video tutorial: 
https://www.youtube.com/watch?v=6WtA2dUDvPY&t=605s

**Comment by JuanRamos26** [comment]
Listo, Codigo subido en github
![Image](https://github.com/user-attachments/assets/4f4db6b3-756e-42e3-b2cb-f130cf744a4b)

**Comment by jairoserrano** [comment]
adelante
