### ISSUE TITLE
Wireframe #2 (nota)

### ISSUE THREAD

**Issue by JuanRamos26** [ISCOUTB/DG-UTB-Tools#8]
Haces Wireframe de:

- [x] Calcula tu nota

Solo el bosquejo, puede tener cambios a futuro lo ideal es tener idea de lo que vamos hacer

**Comment by jerdiaz** [comment]
Vista web de la opción calcula tu nota
![Image](https://github.com/user-attachments/assets/4c6a33fc-8d29-499d-9fc4-f32772e97b0e)

**Comment by Manuuell** [comment]
Wireframe revisado y aprobado

**Comment by jairoserrano** [comment]
adelante
