### ISSUE TITLE
Wireframe #3 (convertidor)

### ISSUE THREAD

**Issue by JuanRamos26** [ISCOUTB/DG-UTB-Tools#9]
Haces Wireframe de:

- [x] convertidor

Solo el bosquejo, puede tener cambios a futuro lo ideal es tener idea de lo que vamos hacer

**Comment by Manuuell** [comment]
![Screenshot_2024-09-30-10-12-02-328_com.whatsapp-edit.jpg](https://github.com/user-attachments/assets/3ddb8aed-d8f5-4935-b1e7-f70880677e80)


Wireframe convertidor

**Comment by jairoserrano** [comment]
adelante
